# Generated by Django 4.2.9 on 2024-02-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="slug",
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
