# Generated by Django 4.2.9 on 2024-02-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_home_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
